"""
V3 Trading Signal Pipeline Backtest Runner.

For each (asset, historical date), runs the actual 4-stage LLM pipeline
with point-in-time data injected (no live API calls), persists the signal,
then runs the outcome simulator on the signal.

This is the real V3 LLM replay — every signal is generated by the same LLM
chain that runs in production, just with historical data instead of live.

Usage:
    from app.services.v3_backtest_runner import run_v3_backtest

    run_v3_backtest(
        run_id="2025_q4_run1",
        assets=["EURUSD", "XAUUSD", "USA500"],
        start_date="2020-01-01",
        end_date="2025-01-01",
        frequency="weekly",
    )
"""
import json
import logging
import uuid
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from app.core.database import SessionLocal
from app.models.models import BacktestSignal, EconEvent
from app.services.historical_signal_context import build_context
from app.services.signals_stages import (
    run_stage1, run_stage2, run_stage3, run_stage4,
    _make_no_trade,
    _apply_fsm_disagreement_gate,
)
from app.services.signal_outcome_simulator import (
    SignalToSimulate, simulate_signal,
)

logger = logging.getLogger(__name__)


# ─── Historical Pipeline Runner ──────────────────────────────────────────────

def run_historical_pipeline(asset: str, as_of: datetime) -> Optional[Dict[str, Any]]:
    """
    Run the V3 4-stage LLM pipeline for an asset at a historical date,
    using only data publicly known by then.

    Returns the same dict shape as `run_full_pipeline()` — None if context
    can't be built (e.g., missing intraday data).
    """
    logger.info(f"[V3-BT] Running pipeline for {asset} as of {as_of}")

    # 1. Build historical context
    ctx = build_context(asset, as_of)
    if not ctx or not ctx.get("regime_data"):
        logger.warning(f"[V3-BT] No context for {asset} {as_of}")
        return None

    regime_data = ctx["regime_data"]
    macro_data = ctx["macro_data"]
    technicals = ctx["technicals"]
    fsm_context = ctx["fsm_context"]
    asset_class = ctx.get("asset_class", "FX")

    if not technicals:
        logger.warning(f"[V3-BT] No technicals for {asset} {as_of}")
        return None

    # 2. Stage 1 — Regime
    try:
        stage1 = run_stage1(regime_data, fsm_context=fsm_context)
    except Exception as e:
        logger.warning(f"[V3-BT] Stage 1 failed: {e}")
        return None

    # Hard stop: SIDELINES regime — no trading
    if stage1.get("trading_mode") == "SIDELINES":
        return _make_no_trade(asset, asset_class, stage1, {}, "SIDELINES regime", fsm_context, asset)

    # 3. Stage 2 — Macro
    try:
        stage2 = run_stage2(macro_data, stage1, asset, fsm_context=fsm_context)
    except Exception as e:
        logger.warning(f"[V3-BT] Stage 2 failed: {e}")
        return None

    # Hard stop: NEUTRAL/WEAK fundamentals → NO_TRADE
    if stage2.get("fundamental_bias") == "NEUTRAL" and stage2.get("bias_strength") == "WEAK":
        return _make_no_trade(asset, asset_class, stage1, stage2, "Weak fundamentals", fsm_context, asset)

    # 4. Stage 3 — Gatekeeping
    try:
        stage3 = run_stage3(technicals, stage1, stage2, asset)
    except Exception as e:
        logger.warning(f"[V3-BT] Stage 3 failed: {e}")
        return None

    # Hard stop: RED gate with no trigger → NO_TRADE
    if stage3.get("gate_signal") == "RED" and not stage3.get("watch_list_trigger"):
        return _make_no_trade(asset, asset_class, stage1, stage2, "RED gate", fsm_context, asset)

    # 5. Stage 4 — Final aggregator
    try:
        stage4 = run_stage4(stage1, stage2, stage3, asset)
    except Exception as e:
        logger.warning(f"[V3-BT] Stage 4 failed: {e}")
        return None

    # FSM disagreement gate — downgrade trades that fight high-conviction FSM
    stage4 = _apply_fsm_disagreement_gate(stage4, fsm_context, asset)

    # Apply FSM position size override
    if fsm_context and fsm_context.get("available"):
        fsm_pos_mod = fsm_context.get("position_size_modifier", 1.0)
        s1_pos_mod = stage1.get("position_size_modifier", 1.0)
        if fsm_pos_mod < s1_pos_mod:
            stage1["position_size_modifier"] = fsm_pos_mod

    return {
        "asset": asset,
        "asset_class": asset_class,
        "fsm_context": fsm_context,
        "stage1": stage1,
        "stage2": stage2,
        "stage3": stage3,
        "stage4": stage4,
    }


# ─── Signal → Simulation Conversion ──────────────────────────────────────────

def _signal_to_simulation(
    signal_dict: Dict[str, Any],
    asset: str,
    as_of: datetime,
) -> Optional[SignalToSimulate]:
    """
    Convert a V3 pipeline output dict into a SignalToSimulate for the
    outcome simulator. Returns None if the signal isn't tradeable
    (NO_TRADE, WATCH_LIST without prices, etc.)
    """
    stage4 = signal_dict.get("stage4") or {}
    stage3 = signal_dict.get("stage3") or {}

    final_signal = stage4.get("final_signal")
    direction = stage4.get("direction")  # LONG | SHORT | NEUTRAL

    # Only simulate actionable BUY/SELL signals
    if final_signal not in ("BUY", "SELL"):
        return None
    if direction not in ("LONG", "SHORT"):
        return None

    # Prefer Stage 4 prices — they've been through _fix_inverted_levels correction.
    # Fall back to Stage 3 only when Stage 4 didn't output prices (WATCH_LIST paths).
    entry = stage4.get("entry_price") or stage3.get("suggested_entry_price")
    stop = stage4.get("stop_loss") or stage3.get("stop_loss_price")
    target = stage4.get("target") or stage3.get("target_price")
    target_2 = stage4.get("target_2") or stage3.get("target_2_price")
    target_3 = stage4.get("target_3") or stage3.get("target_3_price")

    if entry is None or stop is None or target is None:
        return None

    try:
        return SignalToSimulate(
            asset=asset,
            direction=direction,
            entry_price=float(entry),
            stop_loss=float(stop),
            target_price=float(target),
            target_2=float(target_2) if target_2 is not None else None,
            target_3=float(target_3) if target_3 is not None else None,
            generated_at=as_of,
            entry_window_hours=24,   # 24h limit per spec Section 4.3
            max_hold_days=7,         # Max 7 days per spec Section 5.4
        )
    except (ValueError, TypeError):
        return None


# ─── Signal → DB Persistence ─────────────────────────────────────────────────

def _persist_backtest_signal(
    db_session,
    run_id: str,
    asset: str,
    as_of: datetime,
    signal_dict: Optional[Dict[str, Any]],
    sim_result=None,
    notes: Optional[str] = None,
) -> BacktestSignal:
    """Save one backtest signal + outcome to the BacktestSignal table."""
    stage1 = (signal_dict or {}).get("stage1") or {}
    stage2 = (signal_dict or {}).get("stage2") or {}
    stage3 = (signal_dict or {}).get("stage3") or {}
    stage4 = (signal_dict or {}).get("stage4") or {}
    fsm = (signal_dict or {}).get("fsm_context") or {}

    record = BacktestSignal(
        backtest_run_id=run_id,
        asset=asset,
        as_of_date=as_of,
        # Signal output
        final_signal=stage4.get("final_signal"),
        signal_grade=stage4.get("signal_grade"),
        direction=stage4.get("direction"),
        signal_confidence=stage4.get("signal_confidence"),
        market_regime=stage1.get("market_regime"),
        fundamental_bias=stage2.get("fundamental_bias"),
        gate_signal=stage3.get("gate_signal") if stage3 else None,
        # Prefer Stage 4 corrected prices; fall back to Stage 3
        entry_price=stage4.get("entry_price") or (stage3.get("suggested_entry_price") if stage3 else None),
        stop_loss=stage4.get("stop_loss") or (stage3.get("stop_loss_price") if stage3 else None),
        target_price=stage4.get("target") or (stage3.get("target_price") if stage3 else None),
        target_2_price=stage4.get("target_2") or (stage3.get("target_2_price") if stage3 else None),
        target_3_price=stage4.get("target_3") or (stage3.get("target_3_price") if stage3 else None),
        risk_reward_ratio=stage4.get("risk_reward") or (stage3.get("risk_reward_ratio") if stage3 else None),
        recommended_position_size_pct=stage4.get("recommended_position_size_pct"),
        # FSM
        fsm_composite_score=fsm.get("composite_score"),
        fsm_divergence_category=fsm.get("divergence_category"),
        # Stage outputs
        stage1_output=json.dumps(stage1) if stage1 else None,
        stage2_output=json.dumps(stage2) if stage2 else None,
        stage3_output=json.dumps(stage3) if stage3 else None,
        stage4_output=json.dumps(stage4) if stage4 else None,
        fsm_context_json=json.dumps(fsm) if fsm else None,
        notes=notes,
    )

    # Outcome
    if sim_result:
        record.outcome = sim_result.outcome
        record.entry_triggered = sim_result.entry_triggered
        record.t1_hit = sim_result.t1_hit
        record.t2_hit = sim_result.t2_hit
        record.t3_hit = sim_result.t3_hit
        record.entry_actual_price = sim_result.entry_actual_price
        record.exit_price = sim_result.exit_price
        if sim_result.entry_time:
            try:
                record.entry_time = datetime.fromisoformat(sim_result.entry_time.replace("Z", "+00:00"))
            except Exception:
                pass
        if sim_result.exit_time:
            try:
                record.exit_time = datetime.fromisoformat(sim_result.exit_time.replace("Z", "+00:00"))
            except Exception:
                pass
        record.pnl_pct = sim_result.pnl_pct
        record.r_multiple = sim_result.r_multiple
        record.bars_in_trade = sim_result.bars_in_trade
        record.max_favorable_excursion_pct = sim_result.max_favorable_excursion_pct
        record.max_adverse_excursion_pct = sim_result.max_adverse_excursion_pct

    db_session.add(record)
    try:
        db_session.commit()
    except Exception as e:
        db_session.rollback()
        logger.warning(f"[V3-BT] Failed to persist signal: {e}")

    return record


# ─── News Blackout Filter ────────────────────────────────────────────────────

def _is_news_blackout(as_of: datetime, db_session) -> bool:
    """
    Returns True if there is a HIGH-impact economic event within ±30 minutes
    of as_of. Safe no-op if EconEvent table is empty.
    """
    window_start = as_of - timedelta(minutes=30)
    window_end = as_of + timedelta(minutes=30)
    hit = (
        db_session.query(EconEvent)
        .filter(EconEvent.importance == "high")
        .filter(EconEvent.event_date >= window_start)
        .filter(EconEvent.event_date <= window_end)
        .first()
    )
    return hit is not None


# ─── Date generators ─────────────────────────────────────────────────────────

def _generate_dates(start_date: str, end_date: str, frequency: str) -> List[datetime]:
    """
    Generate a list of UTC datetimes for backtest signals.
    Frequency: 'daily', 'weekly', 'biweekly', 'monthly'.

    Anchors to Wednesdays (weekday=2) for weekly/biweekly to avoid landing
    on weekends. For daily, skips weekends. Each date is 14:00 UTC (9am ET).
    """
    start = datetime.strptime(start_date, "%Y-%m-%d").replace(hour=14)
    end = datetime.strptime(end_date, "%Y-%m-%d").replace(hour=14)

    freq_lower = frequency.lower()

    if freq_lower in ("weekly", "biweekly"):
        delta_days = 7 if freq_lower == "weekly" else 14
        # Move start to next Wednesday so all signal days land mid-week
        days_to_wed = (2 - start.weekday()) % 7
        cur = start + timedelta(days=days_to_wed)
        dates = []
        while cur < end:
            dates.append(cur)
            cur += timedelta(days=delta_days)
        return dates

    if freq_lower == "monthly":
        # First Wednesday of each month
        cur = start
        days_to_wed = (2 - cur.weekday()) % 7
        cur = cur + timedelta(days=days_to_wed)
        dates = []
        while cur < end:
            dates.append(cur)
            # Advance ~30 days, then snap to next Wednesday
            cur += timedelta(days=28)
            days_to_wed = (2 - cur.weekday()) % 7
            cur = cur + timedelta(days=days_to_wed)
        return dates

    # Daily — skip weekends
    dates = []
    cur = start
    while cur < end:
        if cur.weekday() < 5:
            dates.append(cur)
        cur += timedelta(days=1)
    return dates


# ─── Master backtest runner ──────────────────────────────────────────────────

def run_v3_backtest(
    run_id: Optional[str] = None,
    assets: List[str] = None,
    start_date: str = "2020-01-01",
    end_date: str = "2025-01-01",
    frequency: str = "weekly",
    max_signals: Optional[int] = None,
    resume: bool = True,
) -> Dict[str, Any]:
    """
    Run a full V3 backtest across (assets × dates).

    Args:
        run_id: Identifier for this backtest run. Auto-generated if None.
        assets: List of asset names. Defaults to [EURUSD, XAUUSD, USA500].
        start_date: YYYY-MM-DD
        end_date: YYYY-MM-DD
        frequency: 'weekly' (default), 'biweekly', 'monthly', 'daily'
        max_signals: Cap the total number of signals (for testing)
        resume: If True, skip (asset, date) pairs already in DB for this run_id

    Returns: {run_id, signals_generated, errors, metrics}
    """
    assets = assets or ["EURUSD", "XAUUSD", "USA500"]
    run_id = run_id or f"v3_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}"

    dates = _generate_dates(start_date, end_date, frequency)
    total_pairs = len(assets) * len(dates)
    if max_signals:
        total_pairs = min(total_pairs, max_signals)

    logger.info(
        f"[V3-BT] Starting run '{run_id}': {len(assets)} assets × {len(dates)} dates = {total_pairs} pairs"
    )

    db = SessionLocal()
    stats = {
        "run_id": run_id,
        "total_pairs": total_pairs,
        "signals_generated": 0,
        "trades_simulated": 0,
        "errors": 0,
        "skipped_existing": 0,
    }

    try:
        count = 0
        for asset in assets:
            for as_of in dates:
                if max_signals and count >= max_signals:
                    break
                count += 1

                # Resume check: skip if already in DB
                if resume:
                    existing = (
                        db.query(BacktestSignal)
                        .filter(BacktestSignal.backtest_run_id == run_id)
                        .filter(BacktestSignal.asset == asset)
                        .filter(BacktestSignal.as_of_date == as_of)
                        .first()
                    )
                    if existing:
                        stats["skipped_existing"] += 1
                        continue

                logger.info(f"[V3-BT] [{count}/{total_pairs}] {asset} @ {as_of.strftime('%Y-%m-%d')}")

                # News blackout — skip HIGH-impact event window (±30 min)
                if _is_news_blackout(as_of, db):
                    _persist_backtest_signal(db, run_id, asset, as_of, None, notes="News blackout")
                    stats["skipped_existing"] += 1
                    continue

                try:
                    signal_dict = run_historical_pipeline(asset, as_of)
                    if not signal_dict:
                        _persist_backtest_signal(db, run_id, asset, as_of, None, notes="No context")
                        stats["errors"] += 1
                        continue

                    # Convert to simulation if actionable
                    sim_input = _signal_to_simulation(signal_dict, asset, as_of)
                    sim_result = None
                    if sim_input:
                        sim_result = simulate_signal(sim_input)
                        stats["trades_simulated"] += 1

                    _persist_backtest_signal(db, run_id, asset, as_of, signal_dict, sim_result)
                    stats["signals_generated"] += 1
                except Exception as e:
                    logger.exception(f"[V3-BT] Pipeline failed for {asset} {as_of}: {e}")
                    _persist_backtest_signal(db, run_id, asset, as_of, None, notes=f"Error: {e}")
                    stats["errors"] += 1
            else:
                continue
            break  # max_signals reached
    finally:
        db.close()

    logger.info(
        f"[V3-BT] Run '{run_id}' complete: "
        f"{stats['signals_generated']} signals, {stats['trades_simulated']} simulated, "
        f"{stats['errors']} errors, {stats['skipped_existing']} skipped"
    )
    return stats


def get_backtest_results(run_id: str) -> Dict[str, Any]:
    """Aggregate metrics for a completed backtest run, grouped by asset."""
    db = SessionLocal()
    try:
        signals = (
            db.query(BacktestSignal)
            .filter(BacktestSignal.backtest_run_id == run_id)
            .all()
        )

        if not signals:
            return {"run_id": run_id, "total": 0}

        per_asset = {}
        for s in signals:
            asset = s.asset
            if asset not in per_asset:
                per_asset[asset] = {
                    "total_signals": 0,
                    "actionable": 0,
                    "wins": 0,
                    "losses": 0,
                    "open": 0,
                    "not_triggered": 0,
                    "no_trade": 0,
                    "errors": 0,
                    "total_pnl_pct": 0.0,
                    "total_r": 0.0,
                }
            agg = per_asset[asset]
            agg["total_signals"] += 1

            if s.final_signal in ("BUY", "SELL"):
                agg["actionable"] += 1
                if s.outcome == "WIN":
                    agg["wins"] += 1
                elif s.outcome == "LOSS":
                    agg["losses"] += 1
                elif s.outcome == "OPEN":
                    agg["open"] += 1
                elif s.outcome == "ENTRY_NOT_TRIGGERED":
                    agg["not_triggered"] += 1
                if s.pnl_pct is not None:
                    agg["total_pnl_pct"] += s.pnl_pct
                if s.r_multiple is not None:
                    agg["total_r"] += s.r_multiple
            elif s.final_signal in ("NO_TRADE", None):
                agg["no_trade"] += 1
            elif s.final_signal == "WATCH_LIST":
                agg["no_trade"] += 1
            if s.notes and "Error" in s.notes:
                agg["errors"] += 1

        # Compute derived metrics per asset
        for asset, agg in per_asset.items():
            closed = agg["wins"] + agg["losses"]
            agg["closed"] = closed
            agg["win_rate"] = round(agg["wins"] / closed, 3) if closed > 0 else None
            agg["avg_r"] = round(agg["total_r"] / closed, 3) if closed > 0 else None
            agg["total_pnl_pct"] = round(agg["total_pnl_pct"], 2)

        # Portfolio totals
        total_signals = sum(a["total_signals"] for a in per_asset.values())
        total_closed = sum(a["closed"] for a in per_asset.values())
        total_wins = sum(a["wins"] for a in per_asset.values())
        portfolio_win_rate = round(total_wins / total_closed, 3) if total_closed > 0 else None
        portfolio_pnl = round(sum(a["total_pnl_pct"] for a in per_asset.values()), 2)

        # Portfolio-level risk-adjusted metrics
        all_pnl = [s.pnl_pct for s in signals if s.pnl_pct is not None and s.final_signal in ("BUY", "SELL")]
        sharpe_ratio = None
        sortino_ratio = None
        max_drawdown_pct = None
        recovery_factor = None
        if len(all_pnl) >= 2:
            n = len(all_pnl)
            mean_r = sum(all_pnl) / n
            std_r = (sum((x - mean_r) ** 2 for x in all_pnl) / n) ** 0.5
            if std_r > 0:
                sharpe_ratio = round(mean_r / std_r * (252 ** 0.5), 3)
            downside = [x for x in all_pnl if x < 0]
            if downside:
                down_std = (sum(x ** 2 for x in downside) / n) ** 0.5
                if down_std > 0:
                    sortino_ratio = round(mean_r / down_std * (252 ** 0.5), 3)
            cumulative = 0.0; peak = 0.0; max_dd = 0.0
            for r in all_pnl:
                cumulative += r
                peak = max(peak, cumulative)
                max_dd = max(max_dd, peak - cumulative)
            max_drawdown_pct = round(max_dd, 3)
            if max_dd > 0:
                recovery_factor = round(portfolio_pnl / max_dd, 3)

        return {
            "run_id": run_id,
            "total_signals": total_signals,
            "total_closed": total_closed,
            "total_wins": total_wins,
            "portfolio_win_rate": portfolio_win_rate,
            "portfolio_pnl_pct": portfolio_pnl,
            "sharpe_ratio": sharpe_ratio,
            "sortino_ratio": sortino_ratio,
            "max_drawdown_pct": max_drawdown_pct,
            "recovery_factor": recovery_factor,
            "per_asset": per_asset,
        }
    finally:
        db.close()
